name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install -g html-minifier-terser

      - name: Optimize HTML
        run: |
          html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true index.html -o index.html
          html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true 404.html -o 404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true
